import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app-add-role-modal",
  templateUrl: "./add-role-modal.component.html",
  styleUrls: ["./add-role-modal.component.scss"],
})
export class AddRoleModalComponent implements OnInit {
  menusLists = [
    {
      module_id: 1,
      module_name: "Order",
      create: false,
      edit: false,
      view: false,
      delete: false,
      download: false,
      full_access: false,
      assign_owner: false,
    },
    {
      module_id: 2,
      module_name: "Menu",
      create: false,
      edit: false,
      view: false,
      delete: false,
      download: false,
      full_access: false,
      assign_owner: false,
    },
    {
      module_id: 3,
      module_name: "Customer",
      create: false,
      edit: false,
      view: false,
      delete: false,
      download: false,
      full_access: false,
      assign_owner: false,
    },
    {
      module_id: 4,
      module_name: "Rider",
      create: false,
      edit: false,
      view: false,
      delete: false,
      download: false,
      full_access: false,
      assign_owner: false,
    },
    {
      module_id: 5,
      module_name: "Dashboard",
      create: false,
      edit: false,
      view: false,
      delete: false,
      download: false,
      full_access: false,
      assign_owner: false,
    },
    {
      module_id: 6,
      module_name: "Setting",
      create: false,
      edit: false,
      view: false,
      delete: false,
      download: false,
      full_access: false,
      assign_owner: false,
    },
    {
      module_id: 7,
      module_name: "Tenancy",
      create: false,
      edit: false,
      view: false,
      delete: false,
      download: false,
      full_access: false,
      assign_owner: false,
    },
    {
      module_id: 8,
      module_name: "ChatBot",
      create: false,
      edit: false,
      view: false,
      delete: false,
      download: false,
      full_access: false,
      assign_owner: false,
    },
    {
      module_id: 9,
      module_name: "FODS",
      create: false,
      edit: false,
      view: false,
      delete: false,
      download: false,
      full_access: false,
      assign_owner: false,
    },
    {
      module_id: 10,
      module_name: "Loyalty",
      create: false,
      edit: false,
      view: false,
      delete: false,
      download: false,
      full_access: false,
      assign_owner: false,
    },
    {
      module_id: 11,
      module_name: "Coupons",
      create: false,
      edit: false,
      view: false,
      delete: false,
      download: false,
      full_access: false,
      assign_owner: false,
    },
    {
      module_id: 12,
      module_name: "Referals",
      create: false,
      edit: false,
      view: false,
      delete: false,
      download: false,
      full_access: false,
      assign_owner: false,
    },
  ];

  constructor() {}

  ngOnInit(): void {}
}
